export enum BID_STATUS {
    RECEIVED_WITH_ORIGINALS = 'RECEIVED_WITH_ORIGINALS',
    FORM_FILLED = 'FORM_FILLED',
    AWAITING_VERIFICATION = 'AWAITING_VERIFICATION',
    UNDER_REVIEW = 'UNDER_REVIEW',
    RECEIVED = 'RECEIVED',
    REJECTED = 'REJECTED',
    ECP_ACCEPTED = 'ECP_ACCEPTED',
}