export enum BID_TYPE {
    APPLICATION_FOR_ACCESSION = 'APPLICATION_FOR_ACCESSION',
    APPLICATION_FOR_EDIT_REQUISITES = 'APPLICATION_FOR_EDIT_REQUISITES',
    APPLICATION_FOR_ADD_REQUISITES = 'APPLICATION_FOR_ADD_REQUISITES',
}